# docker run --rm -it --volume $PWD:/app --net="host" -w /app ghcr.io/patchlevel/php:8.5
services:
  php:
    image: ghcr.io/patchlevel/php:8.5
    volumes:
      - .:/app
    working_dir: /app
    network_mode: host
    tty: true
    stdin_open: true
    command: sleep infinity

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eventstore
    ports:
      - 5432:5432

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=eventstore
    ports:
      - 3306:3306

  mariadb:
    image: mariadb:12
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=eventstore
    ports:
      - 3307:3306
