name: "Publish docs"

on:
  push:
    branches:
      - "[0-9]+.[0-9]+.x"
  release:
    types:
      - published

jobs:
  trigger:
    uses: patchlevel/.github/.github/workflows/docs-deploy.yml@main
    secrets: inherit
